config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  post 'login', to: 'home#login'

  resources :doctors do
    resources :appointments, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  self.primary_key = 'id'
  
  belongs_to :doctor
  belongs_to :patient

  validate :appointment_time_within_working_hrs

  before_save do
    if id.nil?
      last_id = Appointment.last&.id&.sub('A', '').to_i || '0'.to_i
      self.id = "A#{last_id + 1}"
    end
  end

  def appointment_time_within_working_hrs
    hour = appointment_datetime.hour
    if hour < 8 || hour > 15 || (hour == 15 && appointment_datetime.sec > 0)
      errors.add(:appointment_datetime, 'Appointment time is outside consultation period')
    end
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  self.primary_key = 'id'
  
  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
  self.primary_key = 'id'
  
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    if params[:appointment_date]
      appointment_date = Date.parse(params[:appointment_date])
      @appointments = doctor.appointments.where(appointment_datetime: appointment_date.beginning_of_day..appointment_date.end_of_day)
    else
      @appointments = doctor.appointments
    end
  rescue
    redirect_to action: :index
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(params.permit(:appointment_datetime, :patient_id, :doctor_id))

    if @appointment.invalid?
      render 'new'
    else
      @appointment.save!
      redirect_to action: :index
    end
  end

  def destroy
    Appointment.find(params[:id]).destroy

    redirect_to action: :index
  end

  private

  def doctor
    Doctor.find(params[:doctor_id])
  end
end

app/controllers/bootstrap_controller.rb
class BootstrapController < ApplicationController
  def index
    redirect_to doctor_appointments_path(doctor_id: Doctor.first.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def login
    redirect_to doctor_appointments_path(doctor_id: params[:doctor_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/index.html.erb
<div class="container">
  <h1>My Appointments</h1>

  <div class="mb-3">
    <%= label_tag :appointment_date, 'Appointment Date', class: 'form-label' %>
    <%= date_field_tag :appointment_date, params[:appointment_date], class: 'form-control' %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Appointment Date and Time</th>
        <th>Patient Name</th>
        <th>Patient Age</th>
        <th>Patient Gender</th>
        <th>Cancel</th>
      </tr>
    </thead>
    <tbody>
      <% @appointments.each do |appointment| %>
        <tr>
          <td><%= appointment.id %></td>
          <td><%= appointment.appointment_datetime %> - <%= appointment.appointment_datetime + 1.hour %></td>
          <td><%= appointment.patient.name %>
          <td><%= appointment.patient.age %>
          <td><%= GENDER[appointment.patient.gender] %>
          <td><%= button_to 'Cancel', doctor_appointment_path(doctor_id: appointment.doctor_id, id: appointment.id), class: 'btn btn-primary', method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= javascript_pack_tag 'appointment' %>

app/views/appointments/new.html.erb
<div class="container">
  <h1>Fix appointment</h1>
  
  <% if @appointment.errors.present? %>
    <div class="alert alert-danger" role="alert">
      <%= @appointment.errors.messages.values.join(', ') %>
    </div>
  <% end %>
  <%= form_with(url: doctor_appointments_path) do |form| %>
    <div class="mb-3">
      <%= form.label :appointment_datetime, class: 'form-label' %>
      <%= form.datetime_local_field :appointment_datetime, value: params[:appointment_datetime] || Time.zone.now.to_s(:form), class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= form.label :patient_id, 'Patient', class: 'form-label' %>
      <%= form.select :patient_id, Patient.pluck(:name, :id), { selected: params[:patient_id] }, { class: 'form-select' } %>
    </div>
    <div>
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="container">
  <h1>Login</h1>
  
  <%= form_with(url: login_path) do |form| %>
    <div class="mb-3">
      <%= form.label :doctor_id, 'Doctor', class: 'form-label' %>
      <%= form.select :doctor_id, Doctor.pluck(:name, :id), {}, { class: 'form-select' } %>
    </div>
    <div>
      <%= form.submit 'Login', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointmentSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-warning mb-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar" viewBox="0 0 16 16">
        <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
      </svg>
    </a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if params[:doctor_id].present? %>
          <%= link_to "My appointments", doctor_appointments_path, class: ['nav-link', params[:controller] == 'appointments' && params[:action] == 'index' ? 'active' : ''] %>
          <%= link_to "Fix appointment", new_doctor_appointment_path, class: ['nav-link', params[:controller] == 'appointments' && params[:action] == 'new' ? 'active' : ''] %>

        <% end %>
      </div>
    </div>
    <div class="d-flex">
      <%= link_to "Change user", root_path, class: 'btn' %>
    </div>
  </div>
</nav>